# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import szy_pb2 as proto_dot_szy__pb2


class SZYStub(object):
    """服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Precomputation = channel.unary_unary(
                '/tenseal.SZY/Precomputation',
                request_serializer=proto_dot_szy__pb2.PrecomputationRequest.SerializeToString,
                response_deserializer=proto_dot_szy__pb2.PrecomputationResponse.FromString,
                )
        self.Computation = channel.unary_unary(
                '/tenseal.SZY/Computation',
                request_serializer=proto_dot_szy__pb2.ComputationRequest.SerializeToString,
                response_deserializer=proto_dot_szy__pb2.ComputationResponse.FromString,
                )
        self.OnlineComputation = channel.unary_unary(
                '/tenseal.SZY/OnlineComputation',
                request_serializer=proto_dot_szy__pb2.OnlineComputationRequest.SerializeToString,
                response_deserializer=proto_dot_szy__pb2.OnlineComputationResponse.FromString,
                )
        self.PreOnlineComputation = channel.unary_unary(
                '/tenseal.SZY/PreOnlineComputation',
                request_serializer=proto_dot_szy__pb2.PreOnlineComputationRequest.SerializeToString,
                response_deserializer=proto_dot_szy__pb2.PreOnlineComputationResponse.FromString,
                )
        self.FinalIndex = channel.unary_unary(
                '/tenseal.SZY/FinalIndex',
                request_serializer=proto_dot_szy__pb2.FinalIndexRequest.SerializeToString,
                response_deserializer=proto_dot_szy__pb2.FinalAnsResponse.FromString,
                )


class SZYServicer(object):
    """服务定义
    """

    def Precomputation(self, request, context):
        """Precomputation service - requests ONNX format, ~w
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Computation(self, request, context):
        """Computation message - sends ~u and x_s and receives y_s
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnlineComputation(self, request, context):
        """Computation message - sends ~u and x_s and receives y_s
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreOnlineComputation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SZYServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Precomputation': grpc.unary_unary_rpc_method_handler(
                    servicer.Precomputation,
                    request_deserializer=proto_dot_szy__pb2.PrecomputationRequest.FromString,
                    response_serializer=proto_dot_szy__pb2.PrecomputationResponse.SerializeToString,
            ),
            'Computation': grpc.unary_unary_rpc_method_handler(
                    servicer.Computation,
                    request_deserializer=proto_dot_szy__pb2.ComputationRequest.FromString,
                    response_serializer=proto_dot_szy__pb2.ComputationResponse.SerializeToString,
            ),
            'OnlineComputation': grpc.unary_unary_rpc_method_handler(
                    servicer.OnlineComputation,
                    request_deserializer=proto_dot_szy__pb2.OnlineComputationRequest.FromString,
                    response_serializer=proto_dot_szy__pb2.OnlineComputationResponse.SerializeToString,
            ),
            'PreOnlineComputation': grpc.unary_unary_rpc_method_handler(
                    servicer.PreOnlineComputation,
                    request_deserializer=proto_dot_szy__pb2.PreOnlineComputationRequest.FromString,
                    response_serializer=proto_dot_szy__pb2.PreOnlineComputationResponse.SerializeToString,
            ),
            'FinalIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalIndex,
                    request_deserializer=proto_dot_szy__pb2.FinalIndexRequest.FromString,
                    response_serializer=proto_dot_szy__pb2.FinalAnsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tenseal.SZY', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SZY(object):
    """服务定义
    """

    @staticmethod
    def Precomputation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tenseal.SZY/Precomputation',
            proto_dot_szy__pb2.PrecomputationRequest.SerializeToString,
            proto_dot_szy__pb2.PrecomputationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Computation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tenseal.SZY/Computation',
            proto_dot_szy__pb2.ComputationRequest.SerializeToString,
            proto_dot_szy__pb2.ComputationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnlineComputation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tenseal.SZY/OnlineComputation',
            proto_dot_szy__pb2.OnlineComputationRequest.SerializeToString,
            proto_dot_szy__pb2.OnlineComputationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PreOnlineComputation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tenseal.SZY/PreOnlineComputation',
            proto_dot_szy__pb2.PreOnlineComputationRequest.SerializeToString,
            proto_dot_szy__pb2.PreOnlineComputationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinalIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tenseal.SZY/FinalIndex',
            proto_dot_szy__pb2.FinalIndexRequest.SerializeToString,
            proto_dot_szy__pb2.FinalAnsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
